# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.6.0
maven_group = vt
mod_id = villagernameisprofession
enabled_platforms = fabric,forge,neoforge
mod_name = VillagerNameIsProfession
mod_description = Set Villager name to its profession
mod_authors = VeiTr
mod_license = MIT
mod_sources = https://github.com/VeiTrr/VillagerNameIsProfession
mod_issue_tracker = https://github.com/VeiTrr/VillagerNameIsProfession/issues

# Minecraft properties
minecraft_version = 1.21.11
# Specify the minimum Minecraft version required to run the mod.
# Else, leave it as 0, and it will default to the major version of the Minecraft version specified above. 1.21.1 -> 1.21
minimum_minecraft_version = 1.21.11

# Dependencies
fabric_loader_version = 0.18.5
fabric_api_version = 0.141.3+1.21.11
forge_version = 1.21.11-61.1.5
neoforge_version = 21.11.42

#Fabric
modmenu_version=17.0.0
