# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.6.0
maven_group = vt
archives_name = VillagerNameIsProfession
enabled_platforms = fabric,forge
mod_name = VillagerNameIsProfession
mod_description = Set Villager name to its profession
mod_authors = VeiTr
mod_license = MIT
mod_sources = https://github.com/VeiTrr/VillagerNameIsProfession
mod_issue_tracker = https://github.com/VeiTrr/VillagerNameIsProfession/issues

# Minecraft properties
minecraft_version = 1.19.4
# Specify the minimum Minecraft version required to run the mod.
# Else, leave it as 0, and it will default to the major version of the Minecraft version specified above. 1.21.1 -> 1.21
minimum_minecraft_version = 0
yarn_mappings = 1.19.4+build.2

# Dependencies
fabric_loader_version = 0.14.21
fabric_api_version = 0.87.2+1.19.4
forge_version = 1.19.4-45.3.0

#Fabric
modmenu_version=6.2.1
