modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/VeiTrr/VillagerNameIsProfession/issues"
license = "MIT"

[[mods]]
modId = "villagernameisprofession"
version = "${version}"
displayName = "VillagerNameIsProfession"
authors = "VeiTr"
description = '''
Set Villager name to its profession
'''
logoFile = "icon.png"
displayTest = "NONE"

[[dependencies.villagernameisprofession]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villagernameisprofession]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "villagernameisprofession.mixins.json"
